import { CommandType } from '@prisma/client';
import { Router } from 'express';
import * as base44 from '../controllers/base44.controller.js';
import { create } from '../controllers/command.controller.js';
import { activate, clear } from '../controllers/emergency.controller.js';
import { health } from '../controllers/health.controller.js';
import { update } from '../controllers/settings.controller.js';
import { base44AuthMiddleware } from '../middleware/base44-auth.middleware.js';
import { base44Limiter, commandCreateLimiter, emergencyLimiter } from '../middleware/rate-limit.middleware.js';

export const base44Router = Router();
base44Router.use(base44Limiter, base44AuthMiddleware);
base44Router.get('/health', health);
base44Router.get('/robots', base44.robots);
base44Router.get('/robots/:robotId', base44.robot);
base44Router.get('/robots/:robotId/status', base44.status);
base44Router.get('/robots/:robotId/account', base44.account);
base44Router.get('/robots/:robotId/heartbeat', base44.heartbeat);
base44Router.get('/robots/:robotId/positions', base44.positions);
base44Router.get('/robots/:robotId/orders', base44.orders);
base44Router.get('/robots/:robotId/trades', base44.trades);
base44Router.get('/robots/:robotId/commands', base44.commands);
base44Router.get('/robots/:robotId/logs', base44.logs);
base44Router.get('/robots/:robotId/settings', base44.settings);
base44Router.post('/robots/:robotId/commands', commandCreateLimiter, create);
base44Router.post('/robots/:robotId/start', base44.control(CommandType.START_ROBOT));
base44Router.post('/robots/:robotId/stop', base44.control(CommandType.STOP_ROBOT));
base44Router.post('/robots/:robotId/pause', base44.control(CommandType.PAUSE_ROBOT));
base44Router.post('/robots/:robotId/resume', base44.control(CommandType.RESUME_ROBOT));
base44Router.post('/robots/:robotId/close-all', base44.control(CommandType.CLOSE_ALL_POSITIONS));
base44Router.post('/robots/:robotId/cancel-all-orders', base44.control(CommandType.CANCEL_ALL_PENDING_ORDERS));
base44Router.post('/robots/:robotId/emergency-stop', emergencyLimiter, activate);
base44Router.post('/robots/:robotId/clear-emergency-stop', emergencyLimiter, clear);
base44Router.post('/robots/:robotId/settings', update);
