export const APP_NAME = 'flouba-lite-backend';

export const ENTRY_COMMAND_TYPES = [
  'OPEN_BUY',
  'OPEN_SELL',
  'PLACE_BUY_LIMIT',
  'PLACE_SELL_LIMIT',
  'PLACE_BUY_STOP',
  'PLACE_SELL_STOP',
] as const;

export const CLOSE_COMMAND_TYPES = [
  'CLOSE_POSITION',
  'CLOSE_PARTIAL',
  'CLOSE_ALL_POSITIONS',
  'CANCEL_PENDING_ORDER',
  'CANCEL_ALL_PENDING_ORDERS',
] as const;

export const CONTROL_COMMAND_TYPES = [
  'START_ROBOT',
  'STOP_ROBOT',
  'PAUSE_ROBOT',
  'RESUME_ROBOT',
  'EMERGENCY_STOP',
  'CLEAR_EMERGENCY_STOP',
  'UPDATE_ROBOT_SETTINGS',
  'SYNC_ACCOUNT',
  'SYNC_POSITIONS',
  'SYNC_ORDERS',
  'SYNC_TRADES',
  'MOVE_TO_BREAKEVEN',
  'ENABLE_TRAILING_STOP',
  'DISABLE_TRAILING_STOP',
  'MODIFY_POSITION',
  'MODIFY_PENDING_ORDER',
] as const;

export const TRADE_RELATED_COMMAND_TYPES = [
  ...ENTRY_COMMAND_TYPES,
  'MODIFY_POSITION',
  'MODIFY_PENDING_ORDER',
  'CLOSE_POSITION',
  'CLOSE_PARTIAL',
  'CLOSE_ALL_POSITIONS',
  'CANCEL_PENDING_ORDER',
  'CANCEL_ALL_PENDING_ORDERS',
  'MOVE_TO_BREAKEVEN',
  'ENABLE_TRAILING_STOP',
  'DISABLE_TRAILING_STOP',
] as const;

export const ACTIVE_COMMAND_STATUSES = [
  'QUEUED',
  'VALIDATING',
  'DELIVERED',
  'ACKNOWLEDGED',
  'EXECUTING',
] as const;

export const DELIVERABLE_COMMAND_STATUSES = ['QUEUED'] as const;

export const RISK_REJECTION_CODES = {
  ROBOT_OFFLINE: 'ROBOT_OFFLINE',
  ROBOT_PAUSED: 'ROBOT_PAUSED',
  ROBOT_STOPPED: 'ROBOT_STOPPED',
  EMERGENCY_STOP_ACTIVE: 'EMERGENCY_STOP_ACTIVE',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  AUTOTRADING_DISABLED: 'AUTOTRADING_DISABLED',
  SYMBOL_NOT_ALLOWED: 'SYMBOL_NOT_ALLOWED',
  SYMBOL_BLOCKED: 'SYMBOL_BLOCKED',
  LOT_TOO_SMALL: 'LOT_TOO_SMALL',
  LOT_TOO_LARGE: 'LOT_TOO_LARGE',
  RISK_PERCENT_TOO_HIGH: 'RISK_PERCENT_TOO_HIGH',
  MAX_OPEN_POSITIONS_REACHED: 'MAX_OPEN_POSITIONS_REACHED',
  MAX_SYMBOL_POSITIONS_REACHED: 'MAX_SYMBOL_POSITIONS_REACHED',
  DAILY_LOSS_LIMIT_REACHED: 'DAILY_LOSS_LIMIT_REACHED',
  DRAWDOWN_LIMIT_REACHED: 'DRAWDOWN_LIMIT_REACHED',
  FREE_MARGIN_TOO_LOW: 'FREE_MARGIN_TOO_LOW',
  MARGIN_LEVEL_TOO_LOW: 'MARGIN_LEVEL_TOO_LOW',
  SPREAD_TOO_HIGH: 'SPREAD_TOO_HIGH',
  SESSION_NOT_ALLOWED: 'SESSION_NOT_ALLOWED',
  NEWS_FILTER_BLOCKED: 'NEWS_FILTER_BLOCKED',
  STOP_LOSS_REQUIRED: 'STOP_LOSS_REQUIRED',
  INVALID_STOP_DISTANCE: 'INVALID_STOP_DISTANCE',
  INVALID_TAKE_PROFIT_DISTANCE: 'INVALID_TAKE_PROFIT_DISTANCE',
  REWARD_RISK_TOO_LOW: 'REWARD_RISK_TOO_LOW',
  DUPLICATE_COMMAND: 'DUPLICATE_COMMAND',
  STALE_MARKET_DATA: 'STALE_MARKET_DATA',
  COMMAND_EXPIRED: 'COMMAND_EXPIRED',
  TERMINAL_DISCONNECTED: 'TERMINAL_DISCONNECTED',
  BROKER_DISCONNECTED: 'BROKER_DISCONNECTED',
  INVALID_DIRECTION: 'INVALID_DIRECTION',
  ROBOT_NOT_FOUND: 'ROBOT_NOT_FOUND',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  MARTINGALE_DISABLED: 'MARTINGALE_DISABLED',
} as const;

export const DEFAULT_PAGE_SIZE = 50;
export const MAX_PAGE_SIZE = 200;
export const MAX_JSON_BODY_BYTES = '1mb';
export const STALE_MARKET_DATA_SECONDS = 60;
